pipeline:

  my-build:
    image: docker:latest
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t nginx-static .
    when:
      branch: master
      event: push


